node {
   
    stage('pre-build') { 
        sh '''
            sudo rm -rf docker-java
        '''
        git 'https://github.com/Ikrao/docker-java.git'
       
    }
    stage('Build') {
        
                sh '''
                pwd
                cd docker-spring-boot
                mvn clean package
                sudo docker build -t spring-boot:latest .
                '''
            
        
    }
    stage('run') {
        
        sh'''
                sudo aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 492176696130.dkr.ecr.us-east-1.amazonaws.com
                
                sudo docker tag springboot:latest 492176696130.dkr.ecr.us-east-1.amazonaws.com/springboot:latest
                sudo docker push 492176696130.dkr.ecr.us-east-1.amazonaws.com/springboot:latest
                sudo docker stop springboot && sudo docker rm springboot 
                sudo docker run --name springboot -d -p 8090:8080 -t spring-boot:latest
                echo 'containers running'
        '''
    }
}
